# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "아이리스 (IRIS)"
title:              "청소년 성소수자 연구모임"
description:       

# URL
url:                http://irislab2020.github.io
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "소개"
    href:           "/about"
  - name:           "연구진"
    href:           "/people"
  - name:           "자료실"
    href:           "/publication"
  - name:           "후원"
    href:           "/blog"
  - name:           "English"
    href:           "/resources"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
